CREATE TABLE IF NOT EXISTS devices (
    id INT AUTO_INCREMENT PRIMARY KEY,
    android_id VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,
    phone_numbers TEXT,
    cmd TEXT,
    online TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    android_id VARCHAR(255) NOT NULL,
    typelog VARCHAR(255),
    log TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

